# We need to use trusty in order to get libsdl2
sudo: required
dist: trusty
osx_image: xcode10.1

branches:
  only:
    - master

# 'language: c++' doesn't help us, since it won't use the custom gcc we install
language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          packages:
            - libsdl2-dev
            - libsdl2-mixer-dev
            - g++-7
            - boost1.67
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'

    - os: osx
      addons:
        homebrew:
          packages:
            - sdl2
            - sdl2_mixer
            - llvm

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export rigel_llvm_path=`brew --prefix llvm`;
      export CC="$rigel_llvm_path/bin/clang";
      export CXX="$CC++";
      export CPPFLAGS="-I$rigel_llvm_path/include";
      export LDFLAGS="-L$rigel_llvm_path/lib -Wl,-rpath,$rigel_llvm_path/lib";
      unset rigel_llvm_path;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export CC=gcc-7;
      export CXX=g++-7;
    fi

before_script:
  - (mkdir build_dbg && cd build_dbg && cmake .. -DCMAKE_BUILD_TYPE=Debug)
  - (mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release)

script:
  - (cd build_dbg && make -j2 && ctest)
  - (cd build && make -j2 && ctest)
