# We need to use trusty in order to get libsdl2
sudo: required
dist: trusty

branches:
  only:
    - master

# 'language: c++' doesn't help us, since it won't use the custom gcc we install
language: generic

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - g++-5
      - libboost1.55-dev
      - libboost-program-options1.55-dev
    sources: &sources
      - ubuntu-toolchain-r-test
      - boost-latest

before_script:
  - export CC=gcc-5
  - export CXX=g++-5
  - (mkdir build && cd build && cmake ..)

script:
  - (cd build && make -j2 && ctest)
