os: osx
osx_image: xcode10.2
addons:
  homebrew:
    update: true
    packages:
      - sdl2
      - sdl2_mixer
      - llvm@8
      - z3

branches:
  only:
    - master

# 'language: c++' doesn't help us, since it won't use the custom gcc we install
language: generic

before_install:
  - export CC="/usr/local/opt/llvm@8/bin/clang"
  - export CXX="$CC++"
  - export CPPFLAGS="-I/usr/local/opt/llvm@8/include"
  - export LDFLAGS="-L/usr/local/opt/llvm@8/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

before_script:
  - (mkdir build_dbg && cd build_dbg && cmake .. -DCMAKE_BUILD_TYPE=Debug)
  - (mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release)

script:
  - (cd build_dbg && make -j2 && ctest)
  - (cd build && make -j2 && ctest)
