name: Bundling

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_package_linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo ./docker/ubuntu-deps.sh
    - name: Run CMake
      run: CC=gcc-8 CXX=g++-8 cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cd build && make -j2
    - name: Package (deb)
      run: cd build && cpack -G "DEB" && mv packages/rigelengine.deb packages/rigelengine_linux_x64.deb && mv packages/rigelengine.deb.sha256 packages/rigelengine_linux_x64.deb.sha256
    - name: Run CMake (GL ES version)
      run: CC=gcc-8 CXX=g++-8 cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_GL_ES=ON
    - name: Build (GL ES version)
      run: cd build && make -j2
    - name: Package (deb), GL ES version
      run: cd build && cpack -G "DEB" && mv packages/rigelengine.deb packages/rigelengine_linux_gles_x64.deb && mv packages/rigelengine.deb.sha256 packages/rigelengine_linux_gles_x64.deb.sha256
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu_deb_build
        path: build/packages/*.deb*
